[build]
  command = "yarn run build"

[[redirects]]
  from = "/v2/top-headlines/*"
  to = "https://newsapi.org/v2/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/company.json/*"
  to = "https://opendart.fss.or.kr/api/:splat"
  status = 301
  force = true
  [header]
    Access-Control-Allow-Origin = "*"
    

[[redirects]]
  from = "/v1/*"
  to = "https://api.updatecome.com:8081/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/deepscienceObject/*"
  to = "https://ssproxy.ucloudbiz.olleh.com/v1/AUTH_2197aef3-436e-443d-a060-df0b98a86913/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
