[[redirects]]
  from = "/v2/top-headlines/*"
  to = "https://newsapi.org/v2/top-headlines:splat"
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://opendart.fss.or.kr/api/company.json/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/v1/*"
  to = "https://api.updatecome.com:8081/"
  status = 200
  force = true

[[redirects]]
  from = "/deepscienceObject/*"
  to = "https://ssproxy.ucloudbiz.olleh.com/v1/AUTH_2197aef3-436e-443d-a060-df0b98a86913/"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build settings
[build]
  command = "yarn run build"
